### ISSUE TITLE
Can not use the bot in channels

### ISSUE THREAD

**Issue by KaratekHD** [KaratekHD/Nemesis#89]
**Describe the bug**
The bot just does not react to messages sent in channels.

**To Reproduce**
1. Add the bot to a channel
2. Run `/runs`

**Expected behavior**
The bot replies

**Comment by why-not-try-calmer** [comment]
I am not sure if this is helpful because I don't know what a reply in a channel means, but if this means just sending messages to channels I have just tested with Aiogram and it worked. I am sharing this here since both libraries have the same specs:

1. Add the bot you want to send with to the target channel.
2. Make sure the bot is __admin__, which entails the permission to send messages. This should be the case already if you have added with Telegram Desktop; I have not tested on mobile.
3. Call your library's `send_message(__,__,...)` method, making sure that the first parameter is given a string in the format `@<name of you channel>`. Example for a channel `t.me/pubchess`: `@pubchess`.

**Comment by KaratekHD** [comment]
Ok, turns out the problem is the Handler: When sending a message to a channel, this is the message object:
` {'message_id': 14, 'sender_chat': {'id': -1001691334687, 'type': 'channel', 'title': 'TestChannel', 'username': 'KaratekTest'}, 'date': 1641673598, 'chat': {'id': -1001691334687, 'type': 'channel', 'title': 'TestChannel', 'username': 'KaratekTest'}, 'text': 'Test', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False}`
Since this is not a command object, a MessageFilter is needed instead of a CommandFilter for the bot to actually pick up the message.
Also, this is only gonna get fixed for the  RSS module, as that module is the only one that has features useful for a channel.
